---
 - name: Install ruby and bundle
   hosts: all
   become: true
   vars:
     packages:
     - ruby-full
     - ruby-bundler
     - build-essential
   tasks:
     - name: Install packages
       apt:
         name: "{{ packages }}"
         update_cache: yes
