---
 - name: Install MongoDB
   hosts: all
   become: true
   tasks:
     - name: Add key
       apt_key:
         keyserver: hkp://keyserver.ubuntu.com:80
         id: D68FA50FEA312927

     - name: Copy file
       copy:
         src: ./files/config
         dest: /etc/apt/sources.list.d/mongodb-org-3.2.list

     - name: Install mongo
       apt:
         name: mongodb-org
         update_cache: yes

     - name: Enable mongodb
       systemd:
         name: mongod
         enabled: yes
